import collections.abc
import json

from pathlib import Path

def format_float(number: float, decimals: int = 2) -> str:
    """

    Examples
    --------
    >>> format_float(1.3456)
    '1.35'
    >>> format_float(1.3)
    '1.30'
    """
    rounded = str(round(float(number), decimals))

    if "." not in rounded:
        rounded += "." + "0" * decimals
    elif (n_zeros := len(rounded.split(".")[-1])) != decimals:
        rounded += "0" * (decimals - n_zeros)

    return rounded


def rec_update_dict(dictionary: dict, new: dict, i: int = 0, max_i: int = 20):
    if i == max_i:
        raise RecursionError("Max recursion limit reached")

    for key, value in new.items():
        if isinstance(value, collections.abc.Mapping):
            dictionary[key] = rec_update_dict(
                dictionary.get(key, {}),
                value,
                i=i + 1,
                max_i=max_i,  # pyright: ignore[reportArgumentType]
            )
        else:
            dictionary[key] = value
    return dictionary


def rec_to_tex_macros(
    dictionary: dict | collections.abc.Mapping, pre_key: str = "", i: int = 0, max_i: int = 20
) -> list[str]:
    if i == max_i:
        raise RecursionError("Max recursion limit reached")

    macros = []

    if i == 0:
        macros.append("% Autogenerated macro file.\n")
    for key, value in dictionary.items():
        new_key = ".".join([pre_key, key]) if len(pre_key) > 0 else key
        if any(c.isdigit() for c in new_key):
            raise ValueError(f"Tried to write key '{new_key}' to tex macro but it needs to be only letters.")
        if isinstance(value, collections.abc.Mapping):
            macros += rec_to_tex_macros(value, pre_key=new_key, i=i + 1, max_i=max_i)
        else:
            macros += [
                f"% {new_key}",
                "\\def\\dataX" + new_key.replace(".", "X").replace("_", "") + "/{" + str(value) + "}",
            ]

    return macros


def format_values(obj: object, i: int = 0, max_i: int = 20) -> object:
    if isinstance(obj, str):
        return obj
    if hasattr(obj, "dtype"):
        obj = obj.item()
    if isinstance(obj, float):
        formatted = format_float(obj)
        return formatted
    if isinstance(obj, collections.abc.Mapping):
        new_obj = {}
        for key, value in obj.items():
            new_obj[key] = format_values(value, i=i + 1, max_i=max_i)
        return new_obj
    elif isinstance(obj, collections.abc.Sequence):
        new_obj = []
        for value in obj:
            new_obj.append(format_values(value, i=i + 1, max_i=max_i))

    return obj


def record_information(new_info: dict[str, object] | None = None) -> dict[str, object]:
    info_path = Path("tables/statistics.json")
    info_tex_path = info_path.with_suffix(".tex")

    if info_path.is_file():
        with open(info_path) as infile:
            info = json.load(infile)
    else:
        info = {}

    if new_info is not None:
        info = rec_update_dict(info, new_info)

        info_path.parent.mkdir(exist_ok=True, parents=True)
        with open(info_path, "w") as outfile:
            json.dump(
                format_values(info),
                outfile,
                indent=2,
            )
        with open(info_path) as infile:
            info = json.load(infile)

        info_tex = rec_to_tex_macros(info)
        with open(info_tex_path, "w") as outfile:
            outfile.write("\n".join(info_tex))

    return info
