from __future__ import annotations

import collections.abc
import json
from pathlib import Path

from .config import TABLE_DIR

INFO_PATH = (TABLE_DIR / "statistics.json").resolve()


def format_float(number: float, decimals: int = 2) -> str:
    rounded = str(round(float(number), decimals))
    if "." not in rounded:
        rounded += "." + "0" * decimals
    elif (n_zeros := len(rounded.split(".")[-1])) != decimals:
        rounded += "0" * (decimals - n_zeros)
    return rounded


def merge_nested_dicts(dictionary: dict, new: dict, i: int = 0, max_i: int = 20):
    if i == max_i:
        raise RecursionError("Max recursion limit reached")
    for key, value in new.items():
        if isinstance(value, collections.abc.Mapping):
            dictionary[key] = merge_nested_dicts(dictionary.get(key, {}), value, i=i + 1, max_i=max_i)
        else:
            dictionary[key] = value
    return dictionary


def to_tex_macros(dictionary: dict | collections.abc.Mapping, pre_key: str = "", i: int = 0, max_i: int = 20) -> list[str]:
    if i == max_i:
        raise RecursionError("Max recursion limit reached")
    macros = []
    if i == 0:
        macros.append("% Autogenerated macro file.\n")
    for key, value in dictionary.items():
        new_key = ".".join([pre_key, key]) if len(pre_key) > 0 else key
        if any(c.isdigit() for c in new_key):
            raise ValueError(f"Tried to write key '{new_key}' to tex macro but it needs to be only letters.")
        if isinstance(value, collections.abc.Mapping):
            macros += to_tex_macros(value, pre_key=new_key, i=i + 1, max_i=max_i)
        else:
            macros += [f"% {new_key}", "\\def\\dataX" + new_key.replace(".", "X").replace("_", "") + "/{" + str(value) + "}"]
    return macros


def format_values(obj: object, i: int = 0, max_i: int = 20) -> object:
    if isinstance(obj, str):
        return obj
    if hasattr(obj, "dtype"):
        obj = obj.item()
    if isinstance(obj, float):
        return format_float(obj)
    if isinstance(obj, collections.abc.Mapping):
        new_obj = {}
        for key, value in obj.items():
            new_obj[key] = format_values(value, i=i + 1, max_i=max_i)
        return new_obj
    elif isinstance(obj, collections.abc.Sequence):
        new_obj = []
        for value in obj:
            new_obj.append(format_values(value, i=i + 1, max_i=max_i))
        return new_obj
    return obj


def write_statistics_outputs(new_info: dict[str, object] | None = None) -> dict[str, object]:
    info_tex_path = INFO_PATH.with_suffix(".tex")
    if INFO_PATH.is_file():
        with open(INFO_PATH) as infile:
            info = json.load(infile)
    else:
        info = {}
    if new_info is not None:
        info = merge_nested_dicts(info, new_info)
        INFO_PATH.parent.mkdir(exist_ok=True, parents=True)
        with open(INFO_PATH, "w") as outfile:
            json.dump(format_values(info), outfile, indent=2)
        with open(INFO_PATH) as infile:
            info = json.load(infile)
        info_tex = to_tex_macros(info)
        with open(info_tex_path, "w") as outfile:
            outfile.write("\n".join(info_tex))
    return info
